# Site settings
title: Community Bootcamp 
header-img: img/home-bg.png
email: zaross1@yahoo.com
copyright_name: zaross1
description: > # this means to ignore newlines until "baseurl:"
  Web Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zaross1
learn_profile: zaross1
email_username: zaross1@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
